sshvm: try to use "user" when user@host provided

diff --git a/sshvm b/sshvm
--- a/sshvm
+++ b/sshvm
@@ -6,7 +6,10 @@ if [[ "$1" = "-v" ]]; then
 fi
 
 host="$1"
-if ! grep -Eq "^[0-9.]+$" <<<"$host"; then
+found=$(sed -rn 's/(.*)@.*/\1/p' <<< "$host")
+[[ ! -z "$found" ]] && host=$(sed -r 's/.*@(.*)/\1/' <<< "$host")
+
+if ! ping -c1 "$host" &> /dev/null; then
     if [[ ! -z "$OS_AUTH_URL" ]]; then
         flip=$(nova floating-ip-list | \
             grep $(nova show --minimal "$host" | \
@@ -42,17 +45,21 @@ try_user() {
     sed -nr 's/.*as the user "([^"]+)".*/\1/p' $TMPLOG;
 }
 
-echo -ne "Determining user ...\r" 1>&2;
-found="$(try_user "$host" "$usr")"
-[[ -z "$found" && "$usr" != "root" ]] && found="$(try_user "$host" "root")"
-[[ -z "$found" && "$usr" != "fedora" ]] && found="$(try_user "$host" "fedora")"
-[[ -z "$found" && "$usr" != "cloud-user" ]] && found="$(try_user "$host" "cloud-user")"
-[[ -z "$found" && "$usr" != "rhos-ci" ]] && found="$(try_user "$host" "rhos-ci")"
+if [[ ! -z "$found" ]]; then
+    echo "Using user $found specified together with hostname $found@$host"
+else
+    echo -ne "Determining user ...\r" 1>&2;
+    found="$(try_user "$host" "$usr")"
+    [[ -z "$found" && "$usr" != "root" ]] && found="$(try_user "$host" "root")"
+    [[ -z "$found" && "$usr" != "fedora" ]] && found="$(try_user "$host" "fedora")"
+    [[ -z "$found" && "$usr" != "cloud-user" ]] && found="$(try_user "$host" "cloud-user")"
+    [[ -z "$found" && "$usr" != "rhos-ci" ]] && found="$(try_user "$host" "rhos-ci")"
 
-if [[ -z "$found" ]]; then
-    echo "FAILED to determine the remote user!" 1>&2;
-    exit 1;
-fi;
+    if [[ -z "$found" ]]; then
+        echo "FAILED to determine the remote user!" 1>&2;
+        exit 1;
+    fi;
+fi
 
 echo "Logging in as user $found." 1>&2;
 
